project:
  type: book
  output-dir: ../docs


book:
  title: "Documentation"
  author: "Guillaume Gilles"
  date: "2025-12-14"
  chapters:
    - index.qmd
    - intro.qmd
    - db.qmd

format:
  html:
    theme: cosmo
